About/urls.py
from django.urls import path
import About.views

app_name = "About"

urlpatterns = [
    path('', About.views.index , name='index'),
]

Home/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

app_name = "Home"

urlpatterns = [
    path('', TemplateView.as_view(template_name='Home/Home.html'), name='index'),
]

Tutorial/urls.py
from django.urls import path
import Tutorial.views

app_name = "Tutorial"

urlpatterns = [
    path('', Tutorial.views.index , name='index'),
]

accounts/urls.py
from django.urls import path

from .views import registerView

urlpatterns = [
    path('signup/', registerView, name='signup'),

]

calculator/urls.py
from django.urls import path
from . import views

app_name = "calculator"

urlpatterns = [
    path('', views.index, name='index'),
]

cleaning_calculator_webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls', namespace='home')),
    path('about/', include('About.urls', namespace='about')),
    path('calculator/', include('calculator.urls', namespace='calculator')),
    path('tutorial/', include('Tutorial.urls', namespace='tutorial')),
    path('contact/', include('contact.urls', namespace='contact')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

contact/urls.py
from django.urls import path
import contact.views

app_name = "contact"

urlpatterns = [
    path('', contact.views.index , name='index'),
]

calculator/models.py
from django.db import models


class price_Range(models.Model):
    name = models.CharField(max_length=50, null=False)
    price = models.IntegerField(null=False)


class update_price(models.Model):
    name = models.CharField(max_length=50, null=False)
    rate = models.IntegerField(null=False)

contact/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

contact/forms.py
from django import forms

class EmailForm(forms.Form):
    recipient = forms.EmailField()
    first_name = forms.CharField(max_length=15)
    message = forms.CharField(widget=forms.Textarea)

About/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'About/About.html')

Home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'Home/Home.html')

Tutorial/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'Tutorial/Tutorial.html')

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm

from django.contrib import messages


def registerView(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account Was Created For ' + user)
            return redirect('login')

    context = {'form':form}
    return render(request, 'registration/signup.html', context)

calculator/views.py
from django.shortcuts import render
from calculator.models import update_price


def index(request):
    # it's a simple implementation "update_price.objects.get(name='name_of_field')" is retrieving value from database
    rate1 = update_price.objects.get(name='rate1')
    rate2 = update_price.objects.get(name='rate2')
    rate3 = update_price.objects.get(name='rate3')
    rate4 = update_price.objects.get(name='rate4')
    rate5 = update_price.objects.get(name='rate5')
    rate6 = update_price.objects.get(name='rate6')
    rate7 = update_price.objects.get(name='rate7')
    rate8 = update_price.objects.get(name='rate8')
    rate9 = update_price.objects.get(name='rate9')
    rate10 = update_price.objects.get(name='rate10')
    rate11 = update_price.objects.get(name='rate11')
    rate12 = update_price.objects.get(name='rate12')
    rate13 = update_price.objects.get(name='rate13')
    rate14 = update_price.objects.get(name='rate14')
    # context is showing those values on the webpage, currently those values are hidden and only
    # available for logged in superuser.
    context = {'rates1': rate1, 'rates2': rate2, 'rates3': rate3, 'rates4': rate4, 'rates5': rate5, 'rates6': rate6,
               'rates7': rate7, 'rates8': rate8, 'rates9': rate9, 'rates10': rate10, 'rates11': rate11,
               'rates12': rate12, 'rates13': rate13, 'rates14': rate14, }

    return render(request, 'calculator/newUI.html', context)

contact/views.py
from django.shortcuts import render
from .forms import EmailForm
from django.core.mail import send_mail
from django.conf import settings


def index(request):

    # create a variable to keep track of the form
    messageSent = False

    # check if form has been submitted
    if request.method == 'POST':

        form = EmailForm(request.POST)

        # check if data from the form is clean
        if form.is_valid():
            cd = form.cleaned_data
            subject = "Email from Cleanquotz"
            greetings = "Hello "
            fName = cd['first_name']
            
            message = "We have Received your Query and we will contact you as soon as possible"
            
            # send the email to the recipent
            send_mail(subject, greetings + "Mr " + fName +" "+ message,
                      settings.DEFAULT_FROM_EMAIL, [cd['recipient']])


            cd = form.cleaned_data
            subject = "Email from "
            fName = cd['first_name']
            
            message = cd['message']
            recipient = cd['recipient']
            # send the email to the recipent
            send_mail(subject + fName + " ", message + "\nReply back at " + recipient,
                      settings.DEFAULT_FROM_EMAIL, ['cleanquotz@gmail.com'])

            # set the variable initially created to True
            messageSent = True

    else:
        form = EmailForm()

    return render(request, 'contact/index.html', {

        'form': form,
        'messageSent': messageSent,

    })

About/templates/About/About.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
<p>You're on About Us page</p>
</body>
</html>

Tutorial/templates/Tutorial/Tutorial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tutorial</title>
</head>
<body>
<p>You're on Tutorials Page</p>
</body>
</html>

accounts/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Authentication{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link href="/static/assets/css/signin.css" rel="stylesheet">
</head>
<body>

    {% block content %}
    {% endblock %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

contact/templates/contact/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Serv Peeps | Contact Us</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="/static/assets/img/apple-icon.png">
    <link rel="shortcut icon" type="image/x-icon" href="/static/assets/img/favicon.ico">

    <link rel="stylesheet" href="/static/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/assets/css/templatemo.css">


    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="/static/assets/css/fontawesome.min.css">
<style>
        .main {
            width: 100%;

            text-align: center;
            display: table;
            position: absolute;
            top: 0;
            left: 0;
        }

        .form {
            display: table-cell;
            vertical-align: middle;

        }

        .content-header {
            background-color: #212934;
            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            width: 400px;
            text-align: center;
            padding: 10px 40px;
            border: 1px solid black;
            color: white;
        }

        .content-body {
            background-color: #edf0f4;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: 100px;
            width: 400px;
            text-align: left;
            padding: 10px 40px;
            border: 1px solid black;

        }

        .content-body p {


            width: auto;
            color:#212934;

        }

        .content-body input {
            width: 100%;
            border: none;

        }

        #id_message {
            height: 100px;
            text-align: justify;
        }

        #btn {
            margin: 30px 0px;
            width: auto;
            padding: 5px 20px;
            border-radius: 20px;
            border: none;
            background-color:#59ab6e;
            color: white;
        }
    </style>
</head>

<body>
    <!-- Start Top Nav -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
        <div class="container text-light">
            <div class="w-100 d-flex justify-content-between">
                <div>
                    <i class="fa fa-envelope mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:servpeeps@gmail.com">servpeeps@gmail.com</a>
                    <i class="fa fa-phone mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="tel:(207) 835 1114">(207) 835 1114</a>
                </div>
                <div>
                    <a class="text-light" href="https://fb.com/" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>
                </div>
            </div>
        </div>
    </nav>
    <!-- Close Top Nav -->


    <!-- Header -->
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">

           <img style="max-width: 25%;max-height: 25%;width: auto;height: auto;" src="/static/assets/img/CLEANQUOTZ-01.png"/>

            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                        </li>
                      <!--  <li class="nav-item">
                            <a class="nav-link" href="{% url 'about:index' %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'tutorial:index' %}">Tutorial</a>
                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'calculator:index' %}">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact:index' %}">Contact</a>
                        </li> {% if user.is_authenticated %}
                        <li>
                            <a class="nav-link">Welcome! <strong>{{ user.username }}</strong></a>
                        </li>

                        <li>
                            <a class="nav-link" href="{% url 'accounts:logout' %}"><u>Log Out</u></a>
                        </li>
                         {% else %}
                       <a class="nav-icon position-relative text-decoration-none nav-link" href="{% url 'accounts:login' %}">
                        <i class="fa fa-fw fa-user text-dark mr-3"></i></a>
                          {% endif %}

                    </ul>
                </div>
                </div>
            </div>


    </nav>
    <!-- Close Header -->
    <form method="post">
        {% csrf_token %}
    <div class="my-main">
        <div class="my-form">
            <div class="content-header">
                <h3>Contact Us</h3>
                <p>Please fill out this form</p>
            </div>
            <div class="content-body">
                <div class="data">
                    <p>Full Name*</p>
                    <input type="text" name="first_name" required maxlength="15" id="id_first_name">
                </div>
                <div class="data">
                    <p>Email*</p>
                    <input type="email" name="recipient" required id="id_recipient">
                </div>
                <div class="data">


                    <p>Message*</p>
                    <textarea name="message" cols="40" rows="10" required id="id_message"></textarea>
                </div class="data">
                <div class="data">
                    <input id="btn" type="submit" value="Send">
                </div>
                 <div class="data">
                {% if messageSent %}
                <p style="color:green">We Have Received Your Query</p>
                {% endif %}
            </div>
            </div>

        </div>
    </div>
</form>
    <!-- Start Footer -->
    <footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Serv Peeps</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            USA
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:(207) 835 1114">(207) 835 1114</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">servpeeps@gmail.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="{% url 'home:index' %}">Home</a></li>
                       <!-- <li><a class="text-decoration-none" href="{% url 'about:index' %}">About Us</a></li>-->
                        <li><a class="text-decoration-none" href="{% url 'calculator:index' %}">Calculator</a></li>
                       <!-- <li><a class="text-decoration-none" href="{% url 'tutorial:index' %}">Tutorial</a></li>-->
                        <li><a class="text-decoration-none" href="{% url 'contact:index' %}">Contact</a></li>
                    </ul>
                </div>

            </div>

            <div class="row text-light mb-4">
                <div class="col-12 mb-3">
                    <div class="w-100 my-3 border-top border-light"></div>
                </div>
                <div class="col-auto me-auto">
                    <ul class="list-inline text-left footer-icons">
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
                        </li>
                    </ul>
                </div>

        <div class="w-100 bg-black py-3">
            <div class="container">
                <div class="row pt-2">
                    <div class="col-12">
                        <p class="text-left text-light">
                            Copyright &copy; 2021 Serv Peeps
                            | Designed by <a rel="sponsored" href="#" target="_blank">Unique Design</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>
    <!-- End Footer -->

    <!-- Start Script -->
    <script src="/static/assets/js/jquery-1.11.0.min.js"></script>
    <script src="/static/assets/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="/static/assets/js/bootstrap.bundle.min.js"></script>
    <script src="/static/assets/js/templatemo.js"></script>

    <!-- End Script -->
</body>

</html>